IGNORE_CONFIG_FILE: false

AirBurstSettings:
  durationToFire: 40.0
  knockback: 2.0
  performanceAmount: 15
  radius: 3.0
InfernoPunchDamage: 3.0
addDungeonLoot: false
airBladeBreakableBlockNames:
- minecraft:stone
- minecraft:sand
- minecraft:sandstone
- minecraft:cobblestone
- minecraft:dirt
- minecraft:gravel
- minecraft:brick_block
- minecraft:mossy_cobblestone
- minecraft:stonebrick
- minecraft:clay
- minecraft:hardened_clay
- minecraft:stained_hardened_clay
- minecraft:coal_ore
- minecraft:iron_ore
- minecraft:red_sandstone
- minecraft:grass
- minecraft:grass_path
airBurstSettings:
  damage: 4.0
  push: 2.0
airbladeSettings:
  damage: 3.5
  push: 0.5
allowAirBubbleElytra: false
allowMultiAirbendingWalljump: true
bendableBlocksNames:
- minecraft:stone
- minecraft:cobblestone
- minecraft:sandstone
- minecraft:sandstone:1
- minecraft:sandstone:2
- minecraft:stone_slab
- minecraft:stone_slab:1
- minecraft:stone_slab:3
- minecraft:stone_slab:5
- minecraft:mossy_cobblestone
- minecraft:stone_stairs
- minecraft:glowstone
- minecraft:stonebrick
- minecraft:stonebrick:1
- minecraft:stonebrick:2
- minecraft:stonebrick:3
- minecraft:stone_brick_stairs
- minecraft:end_stone
- minecraft:sandstone_stairs
- minecraft:red_sandstone
- minecraft:red_sandstone:1
- minecraft:red_sandstone:2
- minecraft:red_sandstone_stairs
- minecraft:stone_slab2
- minecraft:end_bricks
- minecraft:dirt
- aroma1997sdimension:miningore
- bigreactors:yellorium
- biomesoplenty:crystal
- biomesoplenty:dirt
- biomesoplenty:dried_sand
- biomesoplenty:gem_block
- biomesoplenty:gem_ore
- biomesoplenty:grass
- biomesoplenty:grass_path
- biomesoplenty:sand
- biomesoplenty:white_sand
- biomesoplenty:white_sandstone
- biomesoplenty:white_sandstone_stairs
- chisel:andesite
- chisel:andesite1
- chisel:andesite2
- chisel:basalt
- chisel:basalt1
- chisel:basalt2
- chisel:block_coal
- chisel:block_coal1
- chisel:block_coal2
- chisel:bricks
- chisel:bricks1
- chisel:bricks2
- chisel:brownstone
- chisel:cobblestone
- chisel:cobblestone1
- chisel:cobblestone2
- chisel:cobblestonemossy
- chisel:cobblestonemossy1
- chisel:cobblestonemossy2
- chisel:concrete_black
- chisel:concrete_black1
- chisel:concrete_black2
- chisel:concrete_blue
- chisel:concrete_blue1
- chisel:concrete_blue2
- chisel:concrete_brown
- chisel:concrete_brown1
- chisel:concrete_brown2
- chisel:concrete_cyan
- chisel:concrete_cyan1
- chisel:concrete_cyan2
- chisel:concrete_gray
- chisel:concrete_gray1
- chisel:concrete_gray2
- chisel:concrete_green
- chisel:concrete_green1
- chisel:concrete_green2
- chisel:concrete_lightblue
- chisel:concrete_lightblue1
- chisel:concrete_lightblue2
- chisel:concrete_lightgray
- chisel:concrete_lightgray1
- chisel:concrete_lightgray2
- chisel:concrete_lime
- chisel:concrete_lime1
- chisel:concrete_lime2
- chisel:concrete_magenta
- chisel:concrete_magenta1
- chisel:concrete_magenta2
- chisel:concrete_orange
- chisel:concrete_orange1
- chisel:concrete_orange2
- chisel:concrete_pink
- chisel:concrete_pink1
- chisel:concrete_pink2
- chisel:concrete_purple
- chisel:concrete_purple1
- chisel:concrete_purple2
- chisel:concrete_red
- chisel:concrete_red1
- chisel:concrete_red2
- chisel:concrete_white
- chisel:concrete_white1
- chisel:concrete_white2
- chisel:concrete_yellow
- chisel:concrete_yellow1
- chisel:concrete_yellow2
- chisel:diorite
- chisel:diorite1
- chisel:diorite2
- chisel:dirt
- chisel:endstone
- chisel:endstone1
- chisel:endstone2
- chisel:glass
- chisel:glass1
- chisel:glassdyedblack
- chisel:glassdyedblue
- chisel:glassdyedbrown
- chisel:glassdyedcyan
- chisel:glassdyedgray
- chisel:glassdyedgreen
- chisel:glassdyedlightblue
- chisel:glassdyedlightgray
- chisel:glassdyedlime
- chisel:glassdyedmagenta
- chisel:glassdyedorange
- chisel:glassdyedpink
- chisel:glassdyedpurple
- chisel:glassdyedred
- chisel:glassdyedwhite
- chisel:glassdyedyellow
- chisel:glasspane
- chisel:glasspane1
- chisel:glasspanedyedblack
- chisel:glasspanedyedblue
- chisel:glasspanedyedbrown
- chisel:glasspanedyedcyan
- chisel:glasspanedyedgray
- chisel:glasspanedyedgreen
- chisel:glasspanedyedlightblue
- chisel:glasspanedyedlightgray
- chisel:glasspanedyedlime
- chisel:glasspanedyedmagenta
- chisel:glasspanedyedorange
- chisel:glasspanedyedpink
- chisel:glasspanedyedpurple
- chisel:glasspanedyedred
- chisel:glasspanedyedwhite
- chisel:glasspanedyedyellow
- chisel:glowstone
- chisel:glowstone1
- chisel:glowstone2
- chisel:granite
- chisel:granite1
- chisel:granite2
- chisel:hardenedclay
- chisel:hardenedclay1
- chisel:hardenedclay2
- chisel:lavastone
- chisel:lavastone1
- chisel:lavastone2
- chisel:limestone
- chisel:limestone1
- chisel:limestone2
- chisel:marble
- chisel:marble1
- chisel:marble2
- chisel:marblepillar
- chisel:netherbrick
- chisel:netherrack
- chisel:prismarine
- chisel:prismarine1
- chisel:prismarine2
- chisel:quartz
- chisel:quartz1
- chisel:sandstone-scribbles
- chisel:sandstonered
- chisel:sandstonered-scribbles
- chisel:sandstonered1
- chisel:sandstonered2
- chisel:sandstoneyellow
- chisel:sandstoneyellow1
- chisel:sandstoneyellow2
- chisel:stonebrick
- chisel:stonebrick1
- chisel:stonebrick2
- chisel:temple
- chisel:templemossy
- chisel:tyrian
- chisel:valentines
- chisel:waterstone
- chisel:waterstone1
- chisel:waterstone2
- growthcraft:salt_ore
- magicalcrops:essenceore
- magicalcrops:essenceoreend
- magicalcrops:essenceorenether
- mekanism:oreblock
- minecraft:stone
- minecraft:sand
- minecraft:sandstone
- minecraft:coal_ore
- minecraft:iron_ore
- minecraft:emerald_ore
- minecraft:diamond_ore
- minecraft:gold_ore
- minecraft:lapis_ore
- minecraft:redstone_ore
- minecraft:red_sandstone
- minecraft:grass
- minecraft:grass_path
- minecraft:netherrack
- minecraft:black_glazed_terracotta
- minecraft:blue_glazed_terracotta
- minecraft:brown_glazed_terracotta
- minecraft:cyan_glazed_terracotta
- minecraft:gray_glazed_terracotta
- minecraft:green_glazed_terracotta
- minecraft:light_blue_glazed_terracotta
- minecraft:lime_glazed_terracotta
- minecraft:magenta_glazed_terracotta
- minecraft:orange_glazed_terracotta
- minecraft:pink_glazed_terracotta
- minecraft:red_glazed_terracotta
- minecraft:silver_glazed_terracotta
- minecraft:white_glazed_terracotta
- minecraft:yellow_glazed_terracotta
- minecraft:brick_stairs
- minecraft:coal_block
- minecraft:concrete
- minecraft:concrete_powder
- minecraft:diamond_ore
- minecraft:double_stone_slab
- minecraft:double_stone_slab2
- minecraft:end_bricks
- minecraft:end_stone
- minecraft:farmland
- minecraft:glass
- minecraft:glass_pane
- minecraft:glowstone
- minecraft:magma
- minecraft:mycelium
- minecraft:nether_brick
- minecraft:nether_brick_stairs
- minecraft:prismarine
- minecraft:quartz_block
- minecraft:quartz_ore
- minecraft:quartz_stairs
- minecraft:red_nether_brick
- minecraft:red_sandstone
- minecraft:red_sandstone_stairs
- minecraft:sandstone_stairs
- minecraft:stained_glass
- minecraft:stained_glass_pane
- minecraft:stone_brick_stairs
- minecraft:stone_slab2
- netherendingores:creative_tab
- netherendingores:ore_end_modded_1
- netherendingores:ore_end_modded_2
- netherendingores:ore_end_vanilla
- netherendingores:ore_nether_modded_1
- netherendingores:ore_nether_modded_2
- netherendingores:ore_nether_vanilla
- netherendingores:ore_other_1
- netherex:amethyst_block
- netherex:amethyst_ore
- netherex:basalt
- netherex:basalt_brick
- netherex:basalt_brick_slab
- netherex:basalt_brick_stairs
- netherex:basalt_pillar
- netherex:basalt_pillar_slab
- netherex:basalt_pillar_stairs
- netherex:basalt_slab
- netherex:basalt_stairs
- netherex:fiery_nether_brick_slab
- netherex:fiery_nether_brick_stairs
- netherex:fiery_nether_brick
- netherex:fiery_netherrack
- netherex:fiery_netherrack_path
- netherex:gloomy_nether_brick
- netherex:gloomy_nether_brick_slab
- netherex:gloomy_nether_brick_stairs
- netherex:gloomy_netherrack
- netherex:gloomy_netherrack_path
- netherex:icy_nether_brick
- netherex:icy_nether_brick_slab
- netherex:icy_nether_brick_stairs
- netherex:icy_netherrack
- netherex:icy_netherrack_path
- netherex:lively_nether_brick
- netherex:lively_nether_brick_slab
- netherex:lively_nether_brick_stairs
- netherex:lively_netherrack
- netherex:lively_netherrack_path
- netherex:netherrack_path
- netherex:quartz_ore
- netherex:red_nether_brick_slab
- netherex:red_nether_brick_stairs
- netherex:rime_ore
- netherex:smooth_basalt
- netherex:smooth_basalt_slab
- netherex:smooth_basalt_stairs
- tconstruct:clear_glass
- tconstruct:clear_stained_glass
- tconstruct:dried_brick_stairs
- tconstruct:dried_clay
- tconstruct:dried_clay_slab
- tconstruct:dried_clay_stairs
- tconstruct:ore
- tconstruct:seared
- twilightforest:castle_brick
- twilightforest:deadrock
- twilightforest:maze_stone
- twilightforest:naga_stone
- twilightforest:nagastone_pillar
- twilightforest:nagastone_pillar_mossy
- twilightforest:nagastone_pillar_weathered
- twilightforest:nagastone_stairs
- twilightforest:nagastone_stairs_mossy
- twilightforest:nagastone_stairs_weathered
- twilightforest:trollsteinn
- twilightforest:underbrick
- minecraft:dirt
- minecraft:dirt:1
- biomesoplenty:dirt:8
- biomesoplenty:dirt
- biomesoplenty:dirt:9
- biomesoplenty:dirt:1
- biomesoplenty:dirt:10
- biomesoplenty:dirt:2
- extraplanets:kepler22b
- galacticraftcore:basic_block_moon:3
- securitycraft:reinforced_dirt
- securitycraft:reinforced_dirt:1
- tconstruct:slime_dirt:3
- tconstruct:slime_dirt:2
- quark:soul_sandstone:1
- quark:soul_sandstone:2
- quark:soul_sandstone_slab
- quark:soul_sandstone_stairs
- quark:gravisand
- railcraft:brick_sandy
- railcraft:brick_sandy:1
- railcraft:brick_sandy:3
- railcraft:brick_sandy:2
- biomesoplenty:grass:3
- biomesoplenty:dirt:9
- biomesoplenty:dirt:1
- biomesoplenty:white_sand
- biomesoplenty:white_sandstone
- biomesoplenty:white_sandstone:1
- biomesoplenty:white_sandstone:2
- biomesoplenty:white_sandstone_stairs
- biomesoplenty:dried_sand
- biomesoplenty:other_slab:1
- extraplanets:orange_sand
- extraplanets:orange_sandstone
- extraplanets:red_sand
- extraplanets:red_sandstone
- lycanitesmobs:desertstonepolished
- lycanitesmobs:desertstone
- lycanitesmobs:desertstonepillar
- lycanitesmobs:desertstonebrick_slab
- lycanitesmobs:desertstone_slab
- lycanitesmobs:desertstonebrick_stairs
- lycanitesmobs:desertstonebrick
- lycanitesmobs:desertstone_slab_double
- natura:nether_heat_sand
- quark:sandy_bricks
- quark:sandy_bricks_stairs
- quark:sandy_bricks_slab
- quark:soul_sandstone
- railcraft:brick_sandy:4
- railcraft:brick_sandy:5
- railcraft:brick_red_sandy
- railcraft:brick_red_sandy:1
- railcraft:brick_red_sandy:2
- railcraft:brick_red_sandy:3
- railcraft:brick_red_sandy:4
- railcraft:brick_red_sandy:5
- securitycraft:reinforced_sandstone
- securitycraft:reinforced_sand
- securitycraft:reinforced_sand:1
- securitycraft:reinforced_sandstone:1
- securitycraft:reinforced_sandstone:2
- securitycraft:reinforced_stairs_sandstone
- securitycraft:reinforced_stone_slabs:2
- securitycraft:reinforced_red_sandstone
- securitycraft:reinforced_red_sandstone:1
- securitycraft:reinforced_red_sandstone:2
- securitycraft:reinforced_stairs_red_sandstone
- securitycraft:reinforced_stone_slabs2
- minecraft:stone
- minecraft:sand
- minecraft:sandstone
- minecraft:cobblestone
- minecraft:dirt
- minecraft:gravel
- minecraft:brick_block
- minecraft:mossy_cobblestone
- minecraft:stonebrick
- minecraft:clay
- minecraft:hardened_clay
- minecraft:stained_hardened_clay
- minecraft:coal_ore
- minecraft:iron_ore
- minecraft:red_sandstone
- minecraft:grass
- minecraft:grass_path
boulderSettings:
  damage: 0.1
  push: 0.1
chiAirBubble: 1.5
chiAirBubbleOneSecond: 0.125
chiAirBubbleTakeDamage: 0.25
chiAirBurst: 4.0
chiAirGust: 0.5
chiAirJump: 0.4
chiAirblade: 1.0
chiBoulderRing: 3.0
chiBuff: 2.0
chiBuffLvl2: 3.0
chiBuffLvl3: 3.5
chiBuffLvl4: 4.0
chiCloudburst: 2.5
chiEarthspike: 3.5
chiExplosion: 3.0
chiExplosionUpgraded: 4.5
chiExplosivePillar: 4.0
chiFireArc: 1.0
chiFireJump: 2.0
chiFireball: 2.0
chiFlamethrowerSecond: 2.5
chiFlamethrowerSecondLvl4_1: 3.75
chiFlamethrowerSecondLvl4_2: 4.25
chiIceShieldCreate: 4.0
chiIceShieldProtect: 0.15
chiInfernoPunch: 3.0
chiLargeInfernoPunch: 6.0
chiLightFire: 2.0
chiLightning: 6.0
chiLightningRaze: 5.0
chiLightningSpear: 4.0
chiMining: 2.0
chiMiningMaster: 0.5
chiPickUpBlock: 1.25
chiPrison: 5.0
chiPushWall: 4.0
chiRavine: 1.5
chiRavineLvl4_1: 2.25
chiSandPrison: 3.0
chiSandstorm: 3.0
chiShockwave: 6.0
chiSmallInfernoPunch: 2.0
chiWall: 2.5
chiWallOneSecond: 0.125
chiWaterArc: 1.0
chiWaterBubble: 1.25
chiWaterCannon: 5.0
chiWaterSkateSecond: 1.5
chiWave: 2.0
cleanseAngles: 10.0
cleanseChiGroupBonus: 2.0
cleanseSearchRadius: 5.0
cloudburstSettings:
  damage: 3.0
  push: 1.5
earthspikeSettings:
  damage: 3.0
  frequency: 4.0
  push: 0.5
  size: 1.0
explosionSettings:
  damage: 6.0
  damageBlocks: true
  explosionSize: 1.0
  fireTime: 2
  push: 1.0
fireAngles: 8.0
fireArcSettings:
  damage: 3.5
  push: 1.0
fireSearchRadius: 4.0
fireballSettings:
  damage: 3.5
  damageBlocks: true
  explosionSize: 1.0
  fireTime: 6
  push: 1.25
floatingBlockSettings:
  damage: 2.0
  push: 1.0
iceBendableBlockNames:
- minecraft:snow
- minecraft:snow_layer
- minecraft:ice
- minecraft:packed_ice
- minecraft:frosted_ice
icePrisonDamage: 2.0
lightningRazeSettings:
  accuracy: 1.0
  bolts: 1
  damage: 2.0
  frequency: 5.0
  speed: 5.0
  ticks: 20
lightningSpearSettings:
  damage: 4.0
  push: 2.0
passiveSettings:
  fireResistance: true
  hasteInWater: true
  noFallDamageAir: true
  waterBreathing: true
plantBendableBlockNames:
- minecraft:tallgrass
- minecraft:wheat
- minecraft:double_grass
- minecraft:waterlily
- minecraft:red_flower
- minecraft:double_plant
- minecraft:leaves
- minecraft:yellow_flower
- minecraft:red_mushroom
- minecraft:brown_mushroom
- minecraft:vine
preventPickupBlockGriefing: false
ravineSettings:
  damage: 3.5
  push: 0.25
sandBlocksNames:
- minecraft:sand
- minecraft:gravel
- quark:sandstone_new
- quark:sandstone_new:1
- quark:sandstone_new:2
- quark:sandstone_new:3
- quark:sandstone_new:4
- quark:sandstone_new:5
- quark:sandstone_bricks_stairs
- quark:soul_sandstone_bricks_stairs
- quark:red_sandstone_bricks_stairs
- minecraft:sand
- minecraft:sand:1
- minecraft:sandstone
- minecraft:sandstone:1
- minecraft:sandstone:2
- minecraft:stone_slab:1
- minecraft:soul_sand
- minecraft:sandstone_stairs
- minecraft:red_sandstone
- minecraft:red_sandstone:1
- minecraft:red_sandstone:2
- minecraft:red_sandstone_stairs
- minecraft:stone_slab2
- atum:sand
- atum:sand_layer
- biomesoplenty:grass:3
- biomesoplenty:dirt:9
- biomesoplenty:dirt:1
- biomesoplenty:white_sandstone
- biomesoplenty:white_sandstone:1
- biomesoplenty:white_sandstone:2
- biomesoplenty:white_sandstone_stairs
- biomesoplenty:dried_sand
- biomesoplenty:other_slab:1
- extraplanets:orange_sand
- extraplanets:orange_sandstone
- biomesoplenty:white_sand
shiftActivateFireDevour: true
sleepChiRegen: 99999.0
wallJumpDelay: 10
wallMomentum: 10.0
wallWaitTime: 10.0
waterArcAngles: 8.0
waterArcBreakableBlockNames:
- minecraft:stone
- minecraft:sand
- minecraft:sandstone
- minecraft:cobblestone
- minecraft:dirt
- minecraft:gravel
- minecraft:brick_block
- minecraft:mossy_cobblestone
- minecraft:stonebrick
- minecraft:clay
- minecraft:hardened_clay
- minecraft:stained_hardened_clay
- minecraft:coal_ore
- minecraft:iron_ore
- minecraft:red_sandstone
- minecraft:grass
- minecraft:grass_path
waterArcSearchRadius: 4.0
waterArcSettings:
  damage: 3.0
  push: 1.0
waterArcTicks: 120.0
waterBendableBlockNames:
- minecraft:snow
- minecraft:snow_layer
- minecraft:ice
- minecraft:packed_ice
- minecraft:frosted_ice
- minecraft:water
- minecraft:flowing_water
waterBubbleAngles: 8.0
waterBubbleSearchRadius: 5.0
waterCannonSettings:
  useWaterCannonParticles: true
  waterCannonAngles: 8.0
  waterCannonDamage: 1.0
  waterCannonKnockbackMult: 1.0
  waterCannonSearchRadius: 3.0
waveSettings:
  damage: 0.25
  push: 2.0
