# WARNING : Any changes to this config file will not take effect!!
# To fix this, set 'IGNORE_CONFIG_FILE: true' --> 'IGNORE_CONFIG_FILE: false'
# This was done to prevent default values in new versions from being overriden
# by outdated config files. By doing this, you will no longer recieve any new
# config defaults...

IGNORE_CONFIG_FILE: true

airBurstHit: 4.0
airGustHit: 3.0
airJump: 2.0
airbladeHit: 3.0
airbubbleProtect: 6.0
blockKill: 4.0
blockPlaced: 5.0
blockThrowHit: 6.5
buffUsed: 2.0
cloudburstHit: 5.0
createBubble: 15.0
earthspikeHit: 3.0
fireHit: 3.0
fireJump: 5.0
fireballHit: 4.5
flamethrowerHit: 0.75
icePrisoned: 10.0
iceShieldCreated: 2.0
iceShieldProtected: 6.0
lightningspearHit: 6.0
litFire: 20.0
madeLightning: 3.0
miningBreakOre: 5.0
miningUse: 10.0
ravineHit: 3.0
sandPrisoned: 9.0
sandstormPickedUp: 5.0
struckWithLightning: 5.0
wallBlockedAttack: 3.0
wallRaised: 1.0
wallReach: 2.0
waterHit: 3.0
waterSkateOneSecond: 1.5
waveHit: 4.0
