# WARNING : Any changes to this config file will not take effect!!
# To fix this, set 'IGNORE_CONFIG_FILE: true' --> 'IGNORE_CONFIG_FILE: false'
# This was done to prevent default values in new versions from being overriden
# by outdated config files. By doing this, you will no longer recieve any new
# config defaults...

IGNORE_CONFIG_FILE: true

availablePerSecond: 1.0
bonusAbility: 6.0
bonusAbilityLevel: 3.0
bonusLearnedBending: 16.0
infiniteInCreative: true
lowChiDebuffs: false
maxAvailableChi: 12.0
maxChiCap: 100.0
regenInBed: 2.0
regenInWater: 1.5
regenOnEarth: 1.5
regenPerSecond: 0.25
