IGNORE_CONFIG_FILE: false

bisonBreedMaxMinutes: 400.0
bisonBreedMinMinutes: 120.0
bisonChestTameness: 1000
bisonFoods:
  minecraft:sugar: 2
  minecraft:hay_block: 75
  minecraft:apple: 10
  minecraft:wheat: 8
  minecraft:potato: 6
  minecraft:golden_carrot: 30
  minecraft:bread: 5
  minecraft:grass: 9
  minecraft:beetroot: 8
  minecraft:carrot: 6
  minecraft:leaves2: 3
  minecraft:baked_potato: 5
  minecraft:leaves: 3
  minecraft:cake: 45
bisonGrassFoodBonus: 5
bisonLeashTameness: 1000
bisonMaxDomestication: 800
bisonMinDomestication: 500
bisonOwnableTameness: 900
bisonRideOneSecondTameness: 3
bisonRiderTameness: 800
maxNumberOfBenders: 0
scrollDropChance:
scrollTradeItems:
scrollType: