# WARNING : Any changes to this config file will not take effect!!
# To fix this, set 'IGNORE_CONFIG_FILE: true' --> 'IGNORE_CONFIG_FILE: false'
# This was done to prevent default values in new versions from being overriden
# by outdated config files. By doing this, you will no longer recieve any new
# config defaults...

IGNORE_CONFIG_FILE: true

benderSettings:
  maxLevel: 7
  maxNumberOfBenders: 3
bisonFoods:
  minecraft:sugar: 2
  minecraft:hay_block: 75
  minecraft:apple: 10
  minecraft:wheat: 8
  minecraft:potato: 6
  minecraft:golden_carrot: 30
  minecraft:bread: 5
  minecraft:grass: 9
  minecraft:beetroot: 8
  minecraft:carrot: 6
  minecraft:leaves2: 3
  minecraft:baked_potato: 5
  minecraft:leaves: 3
  minecraft:cake: 45
bisonSettings:
  airBisonCanBeSterile: false
  airBisonSpawnNaturally: true
  bisonBreedMaxMinutes: 120.0
  bisonBreedMinMinutes: 60.0
  bisonChestTameness: 1000
  bisonGrassFoodBonus: 5
  bisonLeashTameness: 1000
  bisonMaxDomestication: 800
  bisonMinDomestication: 500
  bisonOwnableTameness: 900
  bisonRideOneSecondTameness: 3
  bisonRiderTameness: 800
scrollDropAmounts:
  zombie_pigman:
  - 2
  - 1
  - 1
  - 1
  chicken:
  - 1
  shulker:
  - 4
  - 3
  - 2
  - 1
  - 1
  - 1
  wither_skeleton:
  - 3
  - 1
  - 1
  - 1
  - 1
  magma_cube:
  - 3
  - 2
  - 1
  skeleton:
  - 1
  - 1
  - 1
  - 1
  - 1
  ender_dragon:
  - 7
  - 6
  - 5
  - 4
  - 3
  - 2
  - 1
  bat:
  - 1
  - 1
  husk:
  - 1
  - 1
  blaze:
  - 3
  - 2
  - 2
  - 2
  - 1
  - 2
  - 1
  - 1
  mooshroom:
  - 1
  - 1
  cave_spider:
  - 2
  - 1
  silverfish:
  - 2
  - 1
  - 1
  zombie:
  - 1
  - 1
  - 1
  - 1
  - 1
  witch:
  - 2
  - 2
  - 1
  ghast:
  - 1
  - 1
  - 3
  - 2
  - 1
  parrot:
  - 1
  spider:
  - 1
  - 1
  sheep:
  - 1
  creeper:
  - 1
  - 1
  - 1
  - 1
  - 1
  enderman:
  - 3
  - 2
  - 1
  - 1
scrollDropChances:
  zombie_pigman:
  - 20.0
  - 10.0
  - 5.0
  - 2.5
  chicken:
  - 7.5
  shulker:
  - 40.0
  - 20.0
  - 10.0
  - 5.0
  - 2.5
  - 1.0
  wither_skeleton:
  - 30.0
  - 15.0
  - 10.0
  - 5.0
  - 1.0
  magma_cube:
  - 25.0
  - 15.0
  - 2.5
  skeleton:
  - 7.5
  - 5.0
  - 1.0
  - 10.0
  - 5.0
  ender_dragon:
  - 75.0
  - 65.0
  - 55.0
  - 45.0
  - 35.0
  - 25.0
  - 15.0
  bat:
  - 5.0
  - 1.0
  husk:
  - 15.0
  - 5.0
  blaze:
  - 20.0
  - 10.0
  - 5.0
  - 2.5
  - 0.5
  - 10.0
  - 5.0
  - 1.0
  mooshroom:
  - 5.0
  - 2.5
  cave_spider:
  - 10.0
  - 5.0
  silverfish:
  - 12.5
  - 5.0
  - 2.5
  zombie:
  - 5.0
  - 2.5
  - 1.0
  - 10.0
  - 5.0
  witch:
  - 10.0
  - 5.0
  - 2.5
  ghast:
  - 40.0
  - 20.0
  - 25.0
  - 15.0
  - 5.0
  parrot:
  - 5.0
  spider:
  - 5.0
  - 1.0
  sheep:
  - 5.0
  creeper:
  - 1.0
  - 2.5
  - 0.5
  - 15.0
  - 7.5
  enderman:
  - 25.0
  - 15.0
  - 10.0
  - 2.5
scrollDropTiers:
  zombie_pigman:
  - 1
  - 2
  - 3
  - 4
  chicken:
  - 1
  shulker:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  wither_skeleton:
  - 1
  - 2
  - 3
  - 4
  - 5
  magma_cube:
  - 1
  - 2
  - 3
  skeleton:
  - 1
  - 2
  - 3
  - 1
  - 2
  ender_dragon:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  bat:
  - 1
  - 2
  husk:
  - 1
  - 2
  blaze:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 1
  - 2
  - 3
  mooshroom:
  - 1
  - 2
  cave_spider:
  - 1
  - 1
  silverfish:
  - 1
  - 2
  - 3
  zombie:
  - 1
  - 2
  - 3
  - 1
  - 2
  witch:
  - 1
  - 2
  - 3
  ghast:
  - 1
  - 2
  - 1
  - 2
  - 3
  parrot:
  - 1
  spider:
  - 1
  - 2
  sheep:
  - 1
  creeper:
  - 1
  - 1
  - 2
  - 1
  - 2
  enderman:
  - 1
  - 2
  - 3
  - 4
scrollSettings:
  absoluteChaos: false
  chaos: false
scrollTradeItems:
  minecraft:totem_of_undying 4: air
  minecraft:blaze_rod 1: fire
  minecraft:magma_cream 2: fire
  minecraft:elytra 5: air
  minecraft:diamond 2: all
  minecraft:emerald 3: all
  minecraft:gold_ingot 1: all
  minecraft:dragon_breath 6: air
scrollTypes:
  zombie_pigman:
  - firebending
  - firebending
  - firebending
  - firebending
  chicken:
  - airbending
  shulker:
  - airbending
  - airbending
  - airbending
  - airbending
  - airbending
  - airbending
  wither_skeleton:
  - firebending
  - firebending
  - firebending
  - firebending
  - firebending
  magma_cube:
  - firebending
  - firebending
  - firebending
  skeleton:
  - earthbending
  - earthbending
  - earthbending
  - all
  - all
  ender_dragon:
  - all
  - all
  - all
  - all
  - all
  - all
  - all
  bat:
  - airbending
  - airbending
  husk:
  - sandbending
  - sandbending
  blaze:
  - firebending
  - firebending
  - firebending
  - firebending
  - firebending
  - combustionbending
  - combustionbending
  - combustionbending
  mooshroom:
  - earthbending
  - earthbending
  cave_spider:
  - earthbending
  - earthbending
  silverfish:
  - earthbending
  - earthbending
  - earthbending
  zombie:
  - earthbending
  - earthbending
  - earthbending
  - all
  - all
  witch:
  - all
  - all
  - all
  ghast:
  - firebending
  - firebending
  - combustionbending
  - combustionbending
  - combustionbending
  parrot:
  - airbending
  spider:
  - earthbending
  - earthbending
  sheep:
  - airbending
  creeper:
  - lightningbending
  - combustionbending
  - combustionbending
  - all
  - all
  enderman:
  - all
  - all
  - all
  - all
