# WARNING : Any changes to this config file will not take effect!!
# To fix this, set 'IGNORE_CONFIG_FILE: true' --> 'IGNORE_CONFIG_FILE: false'
# This was done to prevent default values in new versions from being overriden
# by outdated config files. By doing this, you will no longer recieve any new
# config defaults...

IGNORE_CONFIG_FILE: true

abilitySettings:
  generateAbilities: true
  overrideAbilities: true
  powerLevel: 1.0
  useRadialMouse: true
  useRadialNumbers: true
airBladeHit: 3.0
airBurstHit: 4.0
airGustHit: 3.0
airJump: 2.0
airbubbleProtect: 6.0
blockKill: 4.0
blockPlaced: 5.0
blockThrowHit: 6.5
buffUsed: 4.0
cloudburstHit: 5.0
createBubble: 15.0
earthspikeHit: 3.0
fireJump: 5.0
fireShotHit: 3.0
fireballHit: 4.5
flameStrikeHit: 3.0
flamethrowerHit: 0.75
icePrisoned: 10.0
iceShieldCreated: 2.0
iceShieldProtected: 6.0
lightningspearHit: 6.0
madeLightning: 3.0
miningBreakOre: 3.5
miningUse: 2.5
multipleElements: true
ravineHit: 3.0
sandPrisoned: 9.0
sandstormPickedUp: 5.0
setKeepInventory: true
startWithRandomBending: true
struckWithLightning: 5.0
wallBlockedAttack: 3.0
wallRaised: 1.0
wallReach: 2.0
waterHit: 3.0
waterSkateOneSecond: 1.5
waveHit: 4.0
